apiVersion: v1
data:
  MYSQL_HOST: {{ .Values.MYSQL_HOST | b64enc }}
  MYSQL_PASSWORD: {{ .Values.MYSQL_PASSWORD | b64enc }}
kind: Secret
metadata:
  name: dc-lottery-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  tls.crt: {{ .Values.TLS_SIDECAR_CRT | b64enc }}
  tls.key: {{ .Values.TLS_SIDECAR_KEY | b64enc }}
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls